export const data =[
    {
      id:1,
      question:"Which one is bigger than other?",
      answers:[
        {
          text:3,
          correct:false,
        },
        {
          text:6,
          correct:false,
        },
        {
          text:8,
          correct:true,
        },
        {
          text:2,
          correct:false,
        },
      ]
    },
    {
      id:2,
      question:"Which one is smaller than other?",
      answers:[
        {
          text:33,
          correct:false,
        },
        {
          text:56,
          correct:false,
        },
        {
          text:87,
          correct:false,
        },
        {
          text:12,
          correct:true,
        },
      ]
    },
    {
      id:1,
      question:"Which one is equel to ten?",
      answers:[
        {
          text:10,
          correct:true,
        },
        {
          text:11,
          correct:false,
        },
        {
          text:13,
          correct:false,
        },
        {
          text:15,
          correct:false,
        },
      ]
    },
  ]
